import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { getAssets } from "../utils/cardano";
import NftGrid from "../components/NftGrid";
import initLucid from '../utils/lucid'
import { FaGithub, FaLinkedin, FaTwitter } from 'react-icons/fa'
import { handleFromAddress } from '../utils/handles'

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])
  const [handle, setHandle] = useState("")

  useEffect(() => {
    //const lucid = initLucid(walletStore.name)
    if (walletStore.address != "") {
      getAssets(walletStore.address)
        .then((res: any) => {
          setNftList(res.addressInfo.nfts)
        })
      try {
        handleFromAddress(walletStore.address)
          .then((handles: string[]) => {
            if (handles.length > 0) {
              setHandle(handles[0])
            } else {
              setHandle(walletStore.address)
            }
          })
      } catch (e) {
        console.log(e)
      }


    }
  }, [walletStore.address, handle])

  return (
    <div>
      <Head>
        <title>Rodrigo Molina Dacaret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar bg-base-100 px-10">
        <Link href="/" >
          <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl">Rodrigo</a>
          </div>
        </Link>
        <div className="flex-none">
          <WalletConnect />
        </div>
      </div>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content flex-col-reverse lg:flex-row-reverse w-screen items-left justify-evenly">
          <div className="mockup-code mt-5 bg-accent w-3/4 lg:w-5/12">
            <pre data-prefix="1" className="text-neutral"><code>const Rodrigo: Dev ={" {"} </code></pre>
            <pre data-prefix="2" className="text-neutral"><code>     codingSkills:  true,</code></pre>
            <pre data-prefix="3" className="text-neutral"><code>     creativity:  true,</code></pre>
            <pre data-prefix="4" className="text-neutral"><code>     selfDriven:  true,</code></pre>
            <pre data-prefix="5" className="text-neutral"><code>     perseverance:  true,</code></pre>
            <pre data-prefix="6" className="text-neutral"><code>     teamWork:  true,</code></pre>
            <pre data-prefix="7" className="text-neutral"><code>     cardano:  true,</code></pre>
            <pre data-prefix="8" className="bg-neutral text-warning-content"><code>     lovesJpgStore: true</code></pre>
            <pre data-prefix="9" className="text-neutral"><code>{"}"} </code></pre>

          </div>
          <div className="w-3/4 lg:w-1/2 text-center lg:text-left w-80 text-ellipsis">
            <h1 className="text-5xl font-bold text-ellipsis overflow-hidden ">Hey{handle ? ` ${handle}` : ""}! I'm Rodrigo.</h1>

            <p className="py-6 text-xl text-secondary">I am an autodidact web developer, passionate about Cardano and decentralization.</p>
            <div className="flex w-full justify-center lg:justify-start">
              <a href="https://github.com/rodrigomd94" target="_blank" ><button><FaGithub size={"2.5em"} className="m-2" /></button></a>
              <a href="https://www.linkedin.com/in/rodrigo-molina-dacaret-data-and-gis" target="_blank" ><button><FaLinkedin size={"2.5em"} className="m-2" /></button></a>
              <a href="https://twitter.com/bardic_inspirtn" target="_blank"><button><FaTwitter size={"2.5em"} className="m-2" /></button></a>
            </div>
            <Link href="#skills"><button className="btn mt-5">Get To Know Me</button></Link>
          </div>
        </div>
      </div>

      <div className="hero min-h-screen bg-base-100" id="skills" >
        <div className="hero-content flex-col-reverse lg:flex-row w-screen items-left justify-evenly">
          <div className="w-3/4 lg:w-1/2 text-center lg:text-left">
            <table className="table-auto">
              <tbody>
                <tr >
                  <td className="w-2/3"><progress className="progress w-2/3 lg:w-96 lg:mr-5" value="80" max="100"></progress></td>
                  <td>React</td>
                </tr>
                <tr>
                  <td className="w-2/3"><progress className="progress w-2/3  lg:w-96 lg:mr-5" value="70" max="100"></progress></td>
                  <td>NextJS</td>
                </tr>
                <tr>
                  <td className="w-2/3"><progress className="progress w-2/3 lg:w-96" value="68" max="100"></progress></td>
                  <td>Lucid</td>
                </tr>
                <tr>
                  <td className="w-2/3"><progress className="progress w-2/3 lg:w-96" value="66" max="100"></progress></td>
                  <td>PostgreSQL</td>
                </tr>
                <tr>
                  <td className="w-2/3"><progress className="progress w-2/3 lg:w-96" value="40" max="100"></progress></td>
                  <td>CSL</td>
                </tr>
              </tbody>
            </table>
            <Link href="#projects"><button className="btn btn-neutral mt-5">Projects</button></Link>
          </div>
          <div className="w-3/4 lg:w-5/12 text-center lg:text-left">
            <h1 className="text-5xl font-bold mb-5">Some of my skills</h1>
            <p className="text-xl text-secondary">My search for knowledge has led me to learn a wide variety of skills and helped me contribute to open source projects on Cardano.</p>
            <p className="text-italic text-xl mt-5">“A jack of all trades is a master of none, <b>but oftentimes better than a master of one.</b>”</p>
          </div>
        </div>
      </div>

      <div className="bg-base-200 w-full h-screen flex-col justify-center text-center pt-20" id="projects">
        <h1 className="text-5xl lg:text-5xl font-bold">Projects and contributions</h1>

        <div className="carousel w-full align-middle h-2/3" >
          <div id="chat" className="relative flex-col justify-center carousel-item w-full items-center" >
            <div className="text-center lg:text-left px-20" >
              <h1 className="text-3xl lg:text-5xl font-bold text-primary">Project: P2P wallet chat/trading</h1>
              <p className="py-6">POC of a Cardano wallet-to-wallet chat using GUN.js as a decentralized database. It supports multisig transactions for p2p trading.</p>
              <a href="https://cardano-wallet-chat.vercel.app" target="_blank" className="btn btn-accent">See project</a>

            </div>
            <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
              <a href="#cardaworlds" className="btn btn-circle btn-secondary">❮</a>
              <a href="#quickstarter" className="btn btn-circle btn-secondary">❯</a>
            </div>

          </div>

          <div id="quickstarter" className="relative flex-col justify-center carousel-item w-full items-center" >
            <div className="text-center lg:text-left px-20" >
              <h1 className="text-3xl lg:text-5xl font-bold text-primary" >Project: Cardano dapp quickstarter</h1>
              <p className="py-6">Created a quickstarter project to make it easy for anyone to start a dapp on Cardano.</p>
              <p>Made with NextJS, uses Lucid and even includes an example of interacting with Smart Contracts using Helios Lang.</p>
              <a href="https://github.com/rodrigomd94/cardano-dapp-quickstart" target="_blank" className="btn btn-accent">See project</a>
            </div>
            <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
              <a href="#chat" className="btn btn-circle btn-secondary">❮</a>
              <a href="#roundtable" className="btn btn-circle btn-secondary">❯</a>
            </div>
          </div>

          <div id="roundtable" className="relative flex-col justify-center carousel-item w-full items-center" >
            <div className="text-center lg:text-left px-20" >
              <h1 className="text-3xl lg:text-5xl font-bold text-primary">Contribution: ADAO Roundtable</h1>
              <p className="py-6">Contributed on the implementation of signature coordination using GUN.js.</p>
              <a href="https://github.com/ADAOcommunity/round-table" target="_blank" className="btn btn-accent">See project</a>
            </div>
            <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
              <a href="#quickstarter" className="btn btn-circle btn-secondary">❮</a>
              <a href="#minter" className="btn btn-circle btn-secondary">❯</a>
            </div>
          </div>

          <div id="minter" className="relative flex-col justify-center carousel-item w-full items-center " >
            <div className="text-center lg:text-left px-20" >
              <h1 className="text-3xl lg:text-5xl font-bold text-primary" id="projects">Contribution: ADAO NFT minter</h1>
              <p className="py-6">Contributed by adapting the repo for easy adoption by a wider audience.</p>
              <a href="https://github.com/ADAOcommunity/adao-poc-nft" target="_blank" className="btn btn-accent">See project</a>
            </div>
            <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
              <a href="#roundtable" className="btn btn-circle btn-secondary">❮</a>
              <a href="#cardaworlds" className="btn btn-circle btn-secondary">❯</a>
            </div>
          </div>

          <div id="cardaworlds" className="relative flex-col justify-center carousel-item w-full items-center " >
            <div className="text-center lg:text-left px-20" >
              <h1 className="text-3xl lg:text-5xl font-bold text-primary" id="projects">Project: Cardaworlds</h1>
              <p className="py-6">NFT project of 3D procedurally generated planets using Perlin noise.</p>
              <a href="https://cardaworlds.io" target="_blank" className="btn btn-accent">See project</a>
            </div>
            <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
              <a href="#minter" className="btn btn-circle btn-secondary">❮</a>
              <a href="#chat" className="btn btn-circle btn-secondary">❯</a>
            </div>
          </div>
        </div>
        {/*  <div className="flex justify-center w-full py-2 gap-2">
          <Link href="#chat" ><a className="btn btn-secondary btn-xs">1</a></Link>
          <Link href="#quickstarter" ><a className="btn btn-secondary btn-xs">2</a></Link>
          <Link href="#roundtable" ><a className="btn btn-secondary btn-xs">3</a></Link>
          <Link href="#minter" ><a className="btn btn-secondary btn-xs">4</a></Link>
          <Link href="#cardaworlds" ><a className="btn btn-secondary btn-xs">5</a></Link>
        </div> */}
      </div>



      <div className="carousel w-full ">
        <div id="slide1" className="carousel-item relative w-full justify-center bg-base-100">
          <div className="text-center lg:text-left px-10 text-center w-2/3" >

            <p className="py-6 italic">"Rodrigo is a diligent, hard working, technically competent GIS analyst. He has very good communication skills and has been a joy to work with. I highly recommend him to other employers as no task is too difficult. He has the ability to meet deadlines, work independently or part of a collaborative team. Thank you Rodrigo"</p>
            <p> - James Beech</p>
            <p className="text-secondary">Head of Enterprise Information Management at Westpac New Zealand</p>
          </div>
          <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide2" className="btn btn-circle btn-secondary">❮</a>
            <a href="#slide2" className="btn btn-circle btn-secondary">❯</a>
          </div>
        </div>
        <div id="slide2" className="carousel-item relative w-full justify-center">
          <div className="text-center lg:text-left px-10 text-center w-2/3" >
            <p className="py-6 italic">"Rodrigo is quite simply one of the best people I have worked with in tech (...)
              I can not recommend working with Rodrigo high enough. He does work quickly and efficiently, but equally important, he tactfully gives feedback and suggestions when appropriate.
            </p>
            <p> - Jim Cupples</p>
            <p className="text-secondary">CEO/Cofounder at All The Farms</p>
          </div>
          <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide1" className="btn btn-circle btn-secondary">❮</a>
            <a href="#slide1" className="btn btn-circle btn-secondary">❯</a>
          </div>
        </div>

      </div>

      <footer className="footer items-center lg:justify-between justify-center p-4 bg-base-200 text-secondary mt-10">
        <div className="items-center flex-column ">
          <p>Rodrigo Molina Dacaret</p>
          <p>rodrigomd94@gmail.com</p>
        </div>
        <div className="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
          <a href="https://github.com/rodrigomd94" target="_blank" ><button><FaGithub size={"2.5em"} className="m-2" /></button></a>
          <a href="https://www.linkedin.com/in/rodrigo-molina-dacaret-data-and-gis" target="_blank" ><button><FaLinkedin size={"2.5em"} className="m-2" /></button></a>
          <a href="https://twitter.com/bardic_inspirtn" target="_blank"><button><FaTwitter size={"2.5em"} className="m-2" /></button></a>
        </div>
      </footer>

      <div className="mx-40 my-10">
        {/* <NftGrid nfts={nftList} /> */}
      </div>
    </div>
  )
}

export default Home
